spring:
  application:
    name: eureka_server
server:
  port: 9000
eureka:
  client:
    register-with-eureka: false #是否将自己注册到注册中心(如果集群改为true)
    fetch-registry: false #是否从eureka中获取注册信息(如果集群改为true)
    service-url:  #配置暴露给Eureka Client的请求地址
      defaultZone: http://localhost:9000/eureka/
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 4000 #剔除服务间隔