server:
  port: 7001 #服务端口
spring:
  application:
    name: stream_producer #指定服务名
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output:
          destination: itcast-default #指定消息发送的目的地,在rabbitmq中,发送到一个itcast-default的exchange
      binders:  #配置绑定器
        defaultRabbit:
          type: rabbit