server:
  port: 7003 #服务端口
spring:
  application:
    name: stream_consumer #指定服务名
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
  cloud:
    stream:
      instance-count: 2 #消费者总数
      instance-index: 1 #当前消费者的索引(从0开始)
      bindings:
        input:  #内置的获取消息的通道,从itcast-default中获取消息
          destination: itcast-default
        myInput:  #自定义的通道
          destination: itcast-custom-default
          group: group1 #设置消息的组名称(在同一个group中的多个消费者只有一个可以获取到消息并消费)
          consumer:
            partitioned: true  #开启分区支持
      binders:
        defaultRabbit:
          type: rabbit