server:
  port: 9004
spring:
  application:
    name: service-order #服务名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
#配置Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
hystrix:
  command:
    default:
      execution:
        isolation:
#          strategy: ExecutionIsolationStrategy.SEMAPHORE #信号量隔离
#          strategy: ExecutionIsolationStrategy.THREAD #信号量隔离
#          maxConcurrentRequests: 10 #最大信号量上限
          thread:
            timeoutInMilliseconds: 3000 #配置熔断器的默认降级时间,默认是1秒
      circuitBreaker:
        requestVolumeThreshold: 5 #触发熔断的最小请求次数，默认20次/10秒
        sleepWindowInMilliseconds: 10000 #熔断多少秒后去尝试请求
        errorThresholdPercentage: 50 #触发熔断的失败请求最小占比，默认50%

