server:
  port: 7002 #服务端口
spring:
  application:
    name: stream_consumer #指定服务名
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:  #内置的获取消息的通道,从itcast-default中获取消息
          destination: itcast-default
      binders:
        defaultRabbit:
          type: rabbit